# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Item_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category_descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Auction_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_item_desc', models.TextField()),
                ('auction_start_date', models.DateField()),
                ('auction_actual_close_date', models.DateTimeField()),
                ('auctions_planned_close_date', models.DateTimeField()),
                ('auction_item_actual_selling_price', models.IntegerField()),
                ('auction_item_reserve_price', models.IntegerField()),
                ('auction_item_payment_amount', models.IntegerField()),
                ('auction_item_payment_date', models.DateTimeField()),
                ('auction_item_comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_fname', models.CharField(max_length=100)),
                ('bidder_lname', models.CharField(max_length=100)),
                ('bidder_add', models.TextField()),
                ('bidder_email', models.EmailField(max_length=254)),
                ('bidder_date_joined', models.DateField()),
                ('bidder_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_low_price', models.IntegerField()),
                ('bid_preferred_price', models.IntegerField()),
                ('bid_high_price', models.IntegerField()),
                ('bid_comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='auction_items',
            name='auction_item_successful_bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Bidders'),
        ),
    ]
